"use strict";

var url = 'server_url';

function RemoteStore(url) {

    return {
        get: function (id) {
            return ajaxPromise(url + "/" + id, defaults);
        },
        getAll: function (settings) {
            return ajaxPromise(url, defaults)
        },
        add: function (item) {
            var requestSettings = $.extend({}, defaults, {type: "POST", data: JSON.stringify(item)});
            return ajaxPromise(url, requestSettings);
        },
        update: function (id, updateData) {
            var requestSettings = $.extend({}, defaults, {type: 'PUT', data: JSON.stringify(updateData)});
            return ajaxPromise(url + '/' + id, requestSettings);
        },
        delete: function (id) {
            return ajaxPromise(url + '/' + id, {type: 'DELETE'});
        }
    };
}

function LocalStore() {
    var data = [];
    return {
        getAll: function () {
            return data;
        },

        setAll: function (receivedData) {
            data = receivedData
        },

        get: function (id) {
            data.forEach(function (item, index) {
                if (item.id = id) {
                    return data[index];
                }
            });

            return null;
        },

        update: function (id, newItem) {
            data.forEach(function (item, index) {
                if (item.id = id) {
                    data[index] = newItem;
                }
            });
        },

        add: function (item) {
            data.push(item)
        },

        delete: function (id) {
            data.forEach(function (item, index) {
                if (item.id = id) {
                    data.splice(index, 1);
                }
            });
        }

    }
}

function Repository(url) {
    var remoteStore = new RemoteStore(url);
    var localStore = new LocalStore();

    return {
        getAll: function () {
            remoteStore.getAll().then(
                function (data) {
                    localStore.setAll(data);
                    console.log("data : \n");
                    console.log(data);
                },
                repoErrorHandler
            );
        },

        get: function (id) {
            var data = localStore.get(id);

            if (data != null) {
                return data;
            }
            //if not found in local storage
            else {
                remoteStore.get(id).then(
                    function (data) {
                        return data;
                    },
                    repoErrorHandler
                );
            }
        },

        add: function (item) {
            remoteStore.add(item).then(
                function (data) {
                    localStore.add(item);
                    //sent data which has been sent back by the server
                    //contains id generated by backend database
                },
                repoErrorHandler
            );
        },

        update: function (id, newItem) {
            remoteStore.update(id, newItem).then(
                function () {
                    localStore.update(id, newItem)
                },
                repoErrorHandler
            )
        },

        delete: function (id) {
            remoteStore.delete(id).then(
                function () {
                    localStore.delete(id)
                },
                repoErrorHandler
            )
        },

        logLocalStore: function () {
            console.log(localStore.getAll());
        }
    }
}

var defaults = {
    headers: {
        'Content-Type': 'application/json'
    },
    beforeSend: function () {
    },
    complete: function () {
    }
};

var ajaxPromise = function (ajaxUrl, ajaxSetting) {
    return new Promise(function (resolve, reject) {
        $.ajax(ajaxUrl, ajaxSetting).done(resolve).error(function (xhr) {
            errorHandler(reject, xhr)
        });
    });
};

var repoErrorHandler = function (error) {
    alert(error);
};
var errorHandler = function (reject, xhr) {
    var errorCode = xhr.status;
    var errorMessage = xhr.responseJSON.error;

    if (errorCode == "409") {
        reject(function () {
            return errorMessage;
        })
    } else {
        reject(function () {
            return "Server Error";
        })
    }
};

function RecurringRepository() {
    var data = [{"id": 1, "catId": 1, "amount": 300, "day": 22, "tag": "Salary"}];
}

